[package]
name = "ed25519-comparison"
version = "0.1.0"
edition = "2024"

[lib]
name = "ed25519_comparison"
crate-type   = ["rlib", "cdylib"]

[dependencies]
bincode = { version = "2.0.1", default-features = false }
bobcat-sdk = { version = "0.7.4", features = ["panic-revert", "alloc" ] }
crypto-common = "0.1.7"
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["digest"] }
sha2 = { version = "0.10.9", default-features = false }
array-concat = "0.5.5"
mini-alloc = "1.0.0"

[feature]
std = "bobcat-sdk/std"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = true
lto = "fat"
debug = false
rpath = false
debug-assertions = false
incremental = false

[profile.dev]
codegen-units = 16
panic = "unwind"
opt-level = "z"
incremental = true

[features]
std = ["bobcat-sdk/std"]

[dev-dependencies]
proptest = "1.9.0"
